#!/usr/bin/env python3
"""Update the SignGPT publications list from a Google Sheet.

Downloads "Sheet1" (gid=0) of the SignGPT Project Publications spreadsheet as
CSV and regenerates the auto-generated block in ``signgpt/publications.html``
(the content between the ``PUBLICATIONS:START`` / ``PUBLICATIONS:END`` markers).

Usage:
    python3 scripts/update_signgpt_publications.py

The script has no third-party dependencies (uses only the standard library).
"""

from __future__ import annotations

import csv
import html
import io
import os
import re
import sys
import urllib.request
from collections import OrderedDict

# Google Sheet: "SignGPT Project Publications", Sheet1 (gid=0)
SHEET_ID = "1i7OcZxOdhCqVl4zz1hHa7gGystRd9VeFR56oHHP5kzk"
GID = "0"
CSV_URL = (
    f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"
)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET_HTML = os.path.join(REPO_ROOT, "signgpt", "publications.html")

START_MARKER = "<!-- PUBLICATIONS:START (auto-generated by scripts/update_signgpt_publications.py) -->"
END_MARKER = "<!-- PUBLICATIONS:END -->"

# venue string (upper-cased) -> CSS venue class defined in css/style.css
VENUE_CLASS = {
    "ECCV": "venue-eccv",
    "NEURIPS": "venue-neurips",
    "ICCV": "venue-iccv",
    "ICCVW": "venue-iccv",
    "CVIU": "venue-cviu",
    "FG": "venue-fg",
    "CVPR": "venue-cvpr",
    "CVPRW": "venue-cvpr",
    "BMVC": "venue-lrec",
    "IVA": "venue-acm",
    "LREC": "venue-lrec",
}

# publication type -> (badge CSS class, Font Awesome icon)
TYPE_STYLE = {
    "Conference": ("badge-indigo", "fas fa-users"),
    "Journal": ("badge-green", "fas fa-book"),
    "Workshop": ("badge-amber", "fas fa-chalkboard-user"),
}
DEFAULT_TYPE_STYLE = ("badge-gray", "fas fa-file-lines")


def fetch_csv(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def clean(value: str) -> str:
    """Collapse internal newlines/whitespace and trim."""
    return re.sub(r"\s+", " ", (value or "").replace("\xa0", " ")).strip()


def clean_url(value: str) -> str:
    """Trim whitespace and a stray trailing '?' from a URL cell."""
    url = clean(value)
    return url.rstrip("?").strip()


def parse_rows(csv_text: str) -> list[dict]:
    reader = csv.reader(io.StringIO(csv_text))
    rows = list(reader)

    # Locate the header row (contains "Title" and "Authors").
    header_idx = None
    for i, row in enumerate(rows):
        upper = [c.strip().lower() for c in row]
        if "title" in upper and "authors" in upper:
            header_idx = i
            break
    if header_idx is None:
        raise SystemExit("Could not find header row (with 'Title'/'Authors') in sheet.")

    header = [c.strip() for c in rows[header_idx]]
    col = {name.lower(): idx for idx, name in enumerate(header)}

    def get(row, key):
        idx = col.get(key)
        return row[idx] if idx is not None and idx < len(row) else ""

    pubs = []
    for row in rows[header_idx + 1:]:
        title = clean(get(row, "title"))
        if not title:
            continue  # skip blank / trailing rows
        pubs.append(
            {
                "year": clean(get(row, "year")),
                "type": clean(get(row, "publication type")),
                "venue": clean(get(row, "publisher/venue")),
                "title": title,
                "authors": clean(get(row, "authors")),
                "paper_url": clean_url(get(row, "paper url")),
                "arxiv_url": clean_url(get(row, "arxiv url")),
                "code_url": clean_url(get(row, "code url")),
            }
        )
    return pubs


def render_authors(authors: str) -> str:
    parts = [p.strip() for p in authors.split(",") if p.strip()]
    return ", ".join(f"<strong>{html.escape(p)}</strong>" for p in parts)


def render_links(pub: dict) -> str:
    links = []
    if pub["paper_url"]:
        links.append(
            f'<a href="{html.escape(pub["paper_url"])}" target="_blank" rel="noopener" '
            f'class="btn btn-outline btn-xs"><i class="fas fa-file-pdf"></i> Paper</a>'
        )
    if pub["arxiv_url"]:
        links.append(
            f'<a href="{html.escape(pub["arxiv_url"])}" target="_blank" rel="noopener" '
            f'class="btn btn-outline btn-xs"><i class="ai ai-arxiv"></i> arXiv</a>'
        )
    if pub["code_url"]:
        links.append(
            f'<a href="{html.escape(pub["code_url"])}" target="_blank" rel="noopener" '
            f'class="btn btn-outline btn-xs"><i class="fab fa-github"></i> Code</a>'
        )
    return "\n          ".join(links)


def render_item(pub: dict) -> str:
    badge_class, icon = TYPE_STYLE.get(pub["type"], DEFAULT_TYPE_STYLE)
    venue_class = VENUE_CLASS.get(pub["venue"].upper(), "")
    venue_label = html.escape(f'{pub["venue"]} {pub["year"]}'.strip())
    venue_cls = f"venue {venue_class}".strip()
    data_type = pub["type"].lower() or "other"

    meta = f'<span class="{venue_cls}">{venue_label}</span>'
    if pub["type"]:
        meta += f'\n            <span class="badge {badge_class}">{html.escape(pub["type"])}</span>'

    links = render_links(pub)
    links_block = (
        f'\n        <div class="pub-links">\n          {links}\n        </div>' if links else ""
    )

    return f"""      <div class="pub-item reveal" data-type="{html.escape(data_type)}">
        <div class="pub-icon"><i class="{icon}"></i></div>
        <div class="pub-body">
          <div class="pub-title">
            {html.escape(pub["title"])}
          </div>
          <div class="pub-authors">
            {render_authors(pub["authors"])}
          </div>
          <div class="pub-meta">
            {meta}
          </div>
        </div>{links_block}
      </div>"""


def render_block(pubs: list[dict]) -> str:
    # Group by year, most recent first.
    by_year: "OrderedDict[str, list]" = OrderedDict()
    for pub in sorted(pubs, key=lambda p: p["year"], reverse=True):
        by_year.setdefault(pub["year"], []).append(pub)

    sections = []
    for year, items in by_year.items():
        cards = "\n\n".join(render_item(p) for p in items)
        sections.append(
            f'    <!-- ---- {year} ---- -->\n'
            f'    <div class="year-header">{html.escape(year)}</div>\n'
            f'    <div class="pub-list">\n\n{cards}\n\n    </div>'
        )
    return "\n\n".join(sections)


def update_html(block: str) -> None:
    with open(TARGET_HTML, encoding="utf-8") as fh:
        content = fh.read()

    if START_MARKER not in content or END_MARKER not in content:
        raise SystemExit(
            f"Markers not found in {TARGET_HTML}.\n"
            f"Add these two lines around the auto-generated section:\n"
            f"  {START_MARKER}\n  {END_MARKER}"
        )

    new_section = f"{START_MARKER}\n{block}\n    {END_MARKER}"
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    content = pattern.sub(lambda _: new_section, content)

    with open(TARGET_HTML, "w", encoding="utf-8") as fh:
        fh.write(content)


def main() -> None:
    print(f"Downloading Sheet1 from {CSV_URL}")
    csv_text = fetch_csv(CSV_URL)
    pubs = parse_rows(csv_text)
    print(f"Parsed {len(pubs)} publications.")
    block = render_block(pubs)
    update_html(block)
    print(f"Updated {TARGET_HTML}")


if __name__ == "__main__":
    main()
